import { site } from "./site";
import type { LessonVariant } from "../features/lessons/types";

const youtubeChannel = site.socials.find((social) => social.platform === "YouTube")?.url;

export const lessonVariants: LessonVariant[] = [
  {
    id: "law-testimony-en",
    lessonGroupId: "the-law-and-the-testimony",
    language: "en",
    title: "The Law and the Testimony",
    summary: "A foundational Sabbath lesson on testing doctrine according to the law of God and the testimony borne by the prophets, Christ, and the apostles.",
    pdfUrl: "/lessons/The%20Law%20%26%20the%20Testimony_English.pdf",
    videoUrl: youtubeChannel,
    date: "",
    category: "Foundation",
    scriptureReferences: ["Isaiah 8:20"],
    relatedTeachingSlug: "the-law-and-the-testimony",
    featured: true,
  },
  {
    id: "law-testimony-zu",
    lessonGroupId: "the-law-and-the-testimony",
    language: "zu",
    title: "Umthetho Nobufakazi",
    summary: "Isifundo esiyisisekelo seSabatha esihlola imfundiso ngokomthetho kaNkulunkulu nangobufakazi babaprofethi, bukaKristu, nabezithunywa.",
    pdfUrl: "/lessons/Umthetho%20Nobufakazi_IsiZulu.pdf",
    videoUrl: youtubeChannel,
    date: "",
    category: "Foundation",
    scriptureReferences: ["Isaiah 8:20"],
    relatedTeachingSlug: "the-law-and-the-testimony",
    featured: true,
  },
  {
    id: "law-testimony-st",
    lessonGroupId: "the-law-and-the-testimony",
    language: "st",
    title: "Molao le Bopaki",
    summary: "Thuto ya motheo ya Sabatha e lekanyang thuto ka molao wa Modimo le bopaki ba baprofeta, Kreste, le baapostola.",
    pdfUrl: "/lessons/Molao%20le%20Bopaki_Sesotho.pdf",
    videoUrl: youtubeChannel,
    date: "",
    category: "Foundation",
    scriptureReferences: ["Isaiah 8:20"],
    relatedTeachingSlug: "the-law-and-the-testimony",
    featured: true,
  },
  {
    id: "sabbath-ten-commandments-en",
    lessonGroupId: "the-sabbath-and-the-ten-commandments",
    language: "en",
    title: "The Sabbath and the Ten Commandments",
    summary: "A doctrinal study on the seventh-day Sabbath within the royal law and the moral witness of the commandments.",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Sabbath Doctrine",
    scriptureReferences: ["Exodus 20:8-17", "Isaiah 58:13-14"],
    featured: true,
  },
  {
    id: "sabbath-ten-commandments-zu",
    lessonGroupId: "the-sabbath-and-the-ten-commandments",
    language: "zu",
    title: "The Sabbath and the Ten Commandments",
    summary: "A doctrinal study on the seventh-day Sabbath within the royal law and the moral witness of the commandments.",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Sabbath Doctrine",
    scriptureReferences: ["Exodus 20:8-17", "Isaiah 58:13-14"],
    featured: true,
  },
  {
    id: "feasts-of-the-lord-en",
    lessonGroupId: "the-feasts-of-the-lord",
    language: "en",
    title: "The Feasts of the Lord",
    summary: "An appointed-times lesson tracing the holy convocations of Leviticus 23 and their place in sacred time.",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Holy Days",
    scriptureReferences: ["Leviticus 23"],
    featured: true,
  },
  {
    id: "feasts-of-the-lord-st",
    lessonGroupId: "the-feasts-of-the-lord",
    language: "st",
    title: "The Feasts of the Lord",
    summary: "An appointed-times lesson tracing the holy convocations of Leviticus 23 and their place in sacred time.",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Holy Days",
    scriptureReferences: ["Leviticus 23"],
    featured: true,
  },
  {
    id: "clean-unclean-leviticus-11-en",
    lessonGroupId: "clean-and-unclean-leviticus-11",
    language: "en",
    title: "Clean and Unclean: Leviticus 11",
    summary: "A study in dietary holiness, distinguishing what may be eaten from what must be refused before God.",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Dietary Law",
    scriptureReferences: ["Leviticus 11"],
    featured: false,
  },
];
