import type { LessonVariant } from "../features/lessons/types";

export const lessonVariants: LessonVariant[] = [
  {
    id: "law-testimony-en",
    lessonGroupId: "law-testimony",
    language: "en",
    title: "The Law and the Testimony",
    summary: "",
    pdfUrl: "/lessons/The%20Law%20%26%20the%20Testimony_English.pdf",
    date: "",
    category: "Foundation",
    scriptureReferences: ["Isaiah 8:20"],
    relatedTeachingSlug: "the-law-and-the-testimony",
    featured: true,
  },
  {
    id: "law-testimony-zu",
    lessonGroupId: "law-testimony",
    language: "zu",
    title: "Umthetho Nobufakazi",
    summary: "",
    pdfUrl: "/lessons/Umthetho%20Nobufakazi_IsiZulu.pdf",
    date: "",
    category: "Foundation",
    scriptureReferences: ["Isaiah 8:20"],
    relatedTeachingSlug: "the-law-and-the-testimony",
    featured: true,
  },
  {
    id: "law-testimony-st",
    lessonGroupId: "law-testimony",
    language: "st",
    title: "Molao le Bopaki",
    summary: "",
    pdfUrl: "/lessons/Molao%20le%20Bopaki_Sesotho.pdf",
    date: "",
    category: "Foundation",
    scriptureReferences: ["Isaiah 8:20"],
    relatedTeachingSlug: "the-law-and-the-testimony",
    featured: true,
  },
  {
    id: "sabbath-ten-commandments-en",
    lessonGroupId: "sabbath-ten-commandments",
    language: "en",
    title: "The Sabbath and the Ten Commandments",
    summary: "",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Sabbath Doctrine",
    scriptureReferences: ["Exodus 20:8-17", "Isaiah 58:13-14"],
    featured: true,
  },
  {
    id: "sabbath-ten-commandments-zu",
    lessonGroupId: "sabbath-ten-commandments",
    language: "zu",
    title: "The Sabbath and the Ten Commandments",
    summary: "",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Sabbath Doctrine",
    scriptureReferences: ["Exodus 20:8-17", "Isaiah 58:13-14"],
    featured: true,
  },
  {
    id: "feasts-of-the-lord-en",
    lessonGroupId: "feasts-of-the-lord",
    language: "en",
    title: "The Feasts of the Lord",
    summary: "",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Holy Days",
    scriptureReferences: ["Leviticus 23"],
    featured: true,
  },
  {
    id: "feasts-of-the-lord-st",
    lessonGroupId: "feasts-of-the-lord",
    language: "st",
    title: "The Feasts of the Lord",
    summary: "",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Holy Days",
    scriptureReferences: ["Leviticus 23"],
    featured: true,
  },
  {
    id: "clean-unclean-leviticus-11-en",
    lessonGroupId: "clean-unclean-leviticus-11",
    language: "en",
    title: "Clean and Unclean: Leviticus 11",
    summary: "",
    pdfUrl: "/lessons/placeholder.pdf",
    date: "",
    category: "Dietary Law",
    scriptureReferences: ["Leviticus 11"],
    featured: false,
  },
];
